version: "3.8"

services:
    app:
        build: .
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:your-app-key-here
        depends_on:
            - db

    db:
        image: alpine
        container_name: sqlite_db
        command: tail -f /dev/null
        volumes:
            - ./database/database.sqlite:/var/www/html/database/database.sqlite

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
