services:
    app:
        build: .
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=
        depends_on:
            - sqlite

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    sqlite:
        image: alpine
        container_name: sqlite_db
        volumes:
            - ./database:/var/www/html/database
